### ISSUE TITLE
Batch download as PNG and standardizing the image size?

### ISSUE THREAD

**Issue by naeemmrz** [cdk/depict#31]
Hey, 
I was wondering if it was possible to download the 2D depictions as .png in batch instead of going through them one by one?
Also is there any possibility to standardize the depictions, for example, I want my double bond to be of the same in pictures instead of it zooming out to fit it (i.e. making the double bond shorter in larger compounds).
Regards :)

**Comment by johnmay** [comment]
Hi, it uses the CDK library so you just write a small program to do the batching, otherwise you're stuck with one at a time. 

https://github.com/cdk/cdk/wiki/Toolkit-Rosetta#depict-a-molecule

This also gives more options for example laying out in a grid etc. 

Regarding the zooming. This only happens if you provide a width/height and the depiction would be too big it so it has to zoom out to fit but never zoom in (unless ). If you provide -1/-1 to width/height (or omit them completely) then it will make the images as big as needed and therefore never zoom out.

**Comment by johnmay** [comment]
Hope that helps
